apiVersion: v1
kind: Pod
metadata:
  name: kaniko-pod
  namespace: argocd
spec:
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:latest
    volumeMounts:
    - name: kaniko-home
      mountPath: /kaniko/.docker
    - name: secret-storage
      mountPath: /mnt/secrets
      readOnly: true
    env:
    - name: DOCKER_USERNAME
      valueFrom:
        secretKeyRef:
          name: dockerhubcredentials
          key: DOCKER_USERNAME
    - name: DOCKER_PASSWORD
      valueFrom:
        secretKeyRef:
          name: dockerhubcredentials
          key: DOCKER_PASSWORD
  - name: kaniko
    image: gcr.io/kaniko-project/executor:v1.7.0
    volumeMounts:
    - name: kaniko-home
      mountPath: /kaniko/.docker
    - name: secret-storage
      mountPath: /mnt/secrets
      readOnly: true
  volumes:
  - name: kaniko-home
    emptyDir: {}
  - name: secret-storage
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "aws-secrets-manager"