apiVersion: v1
kind: Pod
metadata:
  name: kaniko-pod
  namespace: argocd
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:v1.7.0
    args:
    - "--dockerfile=dockerfile"
    - "--context=/workspace"
    - "--destination=${REGISTRY_URL}${IMAGE_NAME}:${IMAGE_TAG}"
    volumeMounts:
    - name: kaniko-home
      mountPath: /kaniko/.docker
    - name: aws-secrets
      mountPath: /mnt/secrets
      readOnly: true
    env:
    - name: REGISTRY_URL
      value: "docker.io/"
    - name: IMAGE_NAME
      value: "app-nodejs"
    - name: IMAGE_TAG
      value: "latest"
    - name: DOCKER_USERNAME
      valueFrom:
        secretKeyRef:
          name: dockerhubcredentials
          key: username
    - name: DOCKER_PASSWORD
      valueFrom:
        secretKeyRef:
          name: dockerhubcredentials
          key: password
  volumes:
  - name: kaniko-home
    emptyDir: {}
  - name: aws-secrets
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "aws-secrets-manager"