apiVersion: v1
kind: Pod
metadata:
  name: kaniko-pod
spec:
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:v1.7.0
      args:
        - "--dockerfile=dockerfile"
        - "--context=git://github.com/mahmoud254/jenkins_nodejs_example/"
        - "--destination=${env.registry_url}${env.image_name}:${env.image_tag}"
      volumeMounts:
        - name: kaniko-home
          mountPath: /kaniko/.docker
        - name: aws-secrets
          mountPath: /mnt/secrets/aws
          readOnly: true
      env:
        - name: DOCKER_USERNAME
          valueFrom:
            secretKeyRef:
              name: dockerhubcredentials
              key: username
        - name: DOCKER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dockerhubcredentials
              key: password
  volumes:
    - name: kaniko-home
      emptyDir: {}
    - name: aws-secrets
      secret:
        secretName: dockerhubcredentials
        provider: aws-secrets-manager