apiVersion: v1
kind: Pod
metadata:
  name: kaniko-pod
  namespace: argocd
spec:
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:latest
    volumeMounts:
    - name: kaniko-home
      mountPath: /kaniko/.docker
  - name: kaniko
    image: gcr.io/kaniko-project/executor:v1.7.0
    command: ["/kaniko/executor"]
    args:
    - "--dockerfile=/workspace/dockerfile"
    - "--context=/workspace"
    - "--destination=${REGISTRY_URL}${IMAGE_NAME}:${IMAGE_TAG}"
    volumeMounts:
    - name: kaniko-home
      mountPath: /kaniko/.docker
    - name: secret-storage
      mountPath: /workspace/kaniko
      readOnly: true
  volumes:
  - name: kaniko-home
    emptyDir: {}
  - name: secret-storage
    emptyDir: {}
