apiVersion: v1
kind: Pod
metadata:
  name: kaniko-pod
  namespace: argocd
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:v1.7.0
    volumeMounts:
    - name: aws-secrets
      mountPath: /mnt/secrets
      readOnly: true
    env:
    - name: DOCKER_USERNAME
      valueFrom:
        secretKeyRef:
          name: dockerhubcredentials
          key: username
    - name: DOCKER_PASSWORD
      valueFrom:
        secretKeyRef:
          name: dockerhubcredentials
          key: password
  volumes:
  - name: aws-secrets
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "aws-secrets-manager"