apiVersion: v1
kind: Pod
metadata:
  name: kaniko-pod
  namespace: argocd
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command:
    - ls
    volumeMounts:
    - name: aws-secrets
      mountPath: /mnt/secrets
      readOnly: true
  - name: jnlp
    image: jenkins/inbound-agent:4.3-4
    args: ['${computer.jnlpmac}', '${computer.name}']
  volumes:
  - name: aws-secrets
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "aws-secrets-manager"
