apiVersion: v1
kind: Pod
metadata:
  name: kaniko-pod
  namespace: argocd
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:v1.7.0
    command: ["/bin/sh"]
    args:
    - "-c"
    - |
      export DOCKER_USERNAME=$(cat /mnt/secrets/dockerhubcredentials | jq -r '.username')
      export DOCKER_PASSWORD=$(cat /mnt/secrets/dockerhubcredentials | jq -r '.password')
      /kaniko/executor --dockerfile=dockerfile --context=/workspace --destination=${REGISTRY_URL}${IMAGE_NAME}:${IMAGE_TAG} --verbosity=debug
    volumeMounts:
    - name: kaniko-home
      mountPath: /kaniko/.docker
    - name: aws-secrets
      mountPath: /mnt/secrets
      readOnly: true
    env:
    - name: REGISTRY_URL
      value: "docker.io/alaa872/"
    - name: IMAGE_NAME
      value: "app-nodejs"
    - name: IMAGE_TAG
      value: "latest"
  volumes:
  - name: kaniko-home
    emptyDir: {}
  - name: aws-secrets
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "aws-secrets-manager"